### ISSUE TITLE
Weird error started generating when my tokens move

### ISSUE THREAD

**Issue by apoapostolov** [League-of-Foundry-Developers/fvtt-advanced-macros#40]
Macros.js:64 Advanced Macros | TypeError: Cannot read properties of undefined (reading 'update')
    at eval (eval at <anonymous> (Macros.js:59:16), <anonymous>:30:10)
    at Macro.eval (eval at <anonymous> (Macros.js:59:16), <anonymous>:31:7)
    at 🎁Macro.prototype._executeScript#advanced-macros (Macros.js:61:16)
    at 🎁Macro.prototype._executeScript#0 (libWrapper-wrapper.js:187:52)
    at Macro.renderMacro [as renderContent] (Macros.js:210:16)
    at Macro.executeMacro (Macros.js:231:23)
    at 🎁Macro.prototype.execute#0 (libWrapper-wrapper.js:187:52)
    at Proxy.<anonymous> (sequencer.js:108:25)
    at async Proxy.run (func.js:18:9)
    at async Proxy._execute (func.js:26:9)
    at async Proxy.play (sequencer.js:38:31)

**Comment by mclemente** [comment]
I can't reproduce it. I need whatever you're using on Sequencer that tries to run a macro.

**Comment by apoapostolov** [comment]
I found the issue comes from Automated Animations and JB2A x PF2. Sorry for wasting your time, I will bring the issue to them.

**Comment by mclemente** [comment]
No problem.
My guess is that it is a macro that wasn't updated to use `updateSource` instead of `update` and would probably trigger even if Advanced Macros were disabled.
